spring:
  application.name: stirling-pdf-enterprise
  datasource.url: jdbc:postgresql://localhost:5432/postgres
  datasource.driver-class-name: org.postgres.Driver
  datasource.username: postgres
  datasource.password: postgres
  jpa.hibernate.ddl-auto: update
  security:
    saml2:
      relyingparty:
        registration:
          stirling-pdf:
            entity-id: "authentik"
            signing:
              credentials:
                - private-key-location: "classpath:private-key.key"
                  certificate-location: "classpath:cert.crt"
            singlelogout:
              url: "https://authentik.dev.stirlingpdf.com/application/saml/stirling-pdf/slo/binding/post/"
              binding: "POST"
              response-url: "{baseUrl}/login"
            assertingparty:
              entity-id: "authentik"
              metadata-uri: "classpath:metadata/saml_authentik_metadata.xml"
              singlesignon:
                url: "https://authentik.dev.stirlingpdf.com/application/saml/stirling-pdf/sso/binding/post/"
                binding: "POST"
                sign-request: false
              verification.credentials:
                - certificate-location: "classpath:authentik-Self_Signed_Certificate.pem"
              singlelogout:
                url: "https://authentik.dev.stirlingpdf.com/application/saml/stirling-pdf/slo/binding/post/"
                binding: "POST"
                response-url: "{baseUrl}/login"

stirling-pdf:
  enterprise-edition:
    enabled: true # set to 'true' to enable enterprise edition
    key: 3R3T-WFPY-UNRW-LJFA-MMXM-YVJK-WCKY-PCRT
    sso:
      enable-saml2: true # Only enabled for paid enterprise clients (enterpriseEdition.enabled must be true)
      auto-login: true # Enable to auto login to first provided SSO
      auto-create-user: true # set to 'true' to allow auto-creation of non-existing users
      block-registration: false # set to 'true' to deny login with SSO without prior registration by an admin
    custom-metadata:
      auto-update-metadata: false # set to 'true' to automatically update metadata with below values
      author: username # supports text such as 'John Doe' or types such as username to autopopulate with user's username
      creator: Stirling-PDF # supports text such as 'Company-PDF'
      producer: Stirling-PDF # supports text such as 'Company-PDF'
